# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 1
#
# Initialize kernel
/run/initialize
#
/control/verbose 0 #2
/run/verbose 0 #2
/event/verbose 0
/tracking/verbose 0 #1
#/process/verbose 1
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
/gun/particle mu-
/gun/energy 10 MeV
/gun/position 0 0 0
/gun/direction 1 0 0
#
/run/beamOn 100